export const mapPropertyDetailVmToApi = (propertyDetail) => ({
    title: propertyDetail.title,
    notes: propertyDetail.notes,
    email: propertyDetail.email,
    phone: propertyDetail.phone,
    price: propertyDetail.price,
    saleTypeIds: propertyDetail.saleTypes,
    address: propertyDetail.address,
    city: propertyDetail.city,
    provinceId: propertyDetail.province,
    squareMeter: propertyDetail.squareMeter,
    rooms: propertyDetail.rooms,
    bathrooms: propertyDetail.bathrooms,
    locationUrl: propertyDetail.locationUrl,
    mainFeatures: propertyDetail.mainFeatures,
    equipmentIds: propertyDetail.equipments,
    images: propertyDetail.images,
  });